version: '3.3'
services:
  app:
    build: .
    command: ["gunicorn", "-c", "./config.py", "myapp:app()"]
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASS=pass
      - POSTGRES_DB=db
